spring.application.name=spring-ai-eval

spring.ai.ollama.chat.model=llama3.1

spring.ai.openai.api-key=demo
spring.ai.openai.chat.options.model=gpt-3.5-turbo

spring.ai.openai.chat.options.temperature=0.2
spring.threads.virtual.enabled=true